Update main.py
Setting the checkpoint path to none will cause the following error to occur on line 166 when saving the model,
```
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

```